// words.js
const wordBank: string[] = [
  // --- ANIMALS ---
  "LION", "TIGER", "BEAR", "ZEBRA", "HORSE", "MONKEY", "DONKEY", "RABBIT", "KANGAROO", "GIRAFFE",
  "ELEPHANT", "CHEETAH", "LEOPARD", "HIPPO", "RHINO", "PANDA", "KOALA", "GORILLA", "CHIMPANZEE", "LEMUR",
  "SQUIRREL", "CHIPMUNK", "BEAVER", "OTTER", "BADGER", "DEER", "MOOSE", "ELK", "FOX", "WOLF",
  "COYOTE", "HYENA", "JAGUAR", "PANTHER", "LLAMA", "ALPACA", "CAMEL", "SHEEP", "GOAT", "COW",
  "PIG", "CHICKEN", "TURKEY", "DUCK", "GOOSE", "SWAN", "PENGUIN", "OSTRICH", "EAGLE", "HAWK",
  "FALCON", "OWL", "PARROT", "PIGEON", "SPARROW", "ROBIN", "FLAMINGO", "PEACOCK", "STORK", "CRANE",
  "DOLPHIN", "WHALE", "SHARK", "OCTOPUS", "SQUID", "LOBSTER", "CRAB", "SHRIMP", "SEAL", "WALRUS",
  "TURTLE", "LIZARD", "SNAKE", "FROG", "TOAD", "SALAMANDER", "CHAMELEON", "IGUANA", "ALLIGATOR", "CROCODILE",

  // --- SPORTS & HOBBIES ---
  "SOCCER", "TENNIS", "HOCKEY", "RUGBY", "CRICKET", "GOLF", "BOXING", "KARATE", "SURFING", "SKIING",
  "ROWING", "SAILING", "DIVING", "CYCLING", "RUNNING", "JOGGING", "WALKING", "HIKING", "CAMPING", "FISHING",
  "BOWLING", "BILLIARDS", "DANCE", "BALLET", "CHESS", "CARDS", "GAMING", "COOKING", "BAKING", "READING",
  "WRITING", "PAINTING", "DRAWING", "SKETCHING", "PHOTOGRAPHY", "GARDENING", "SEWING", "KNITTING", "CRAFTING", "SINGING",
  "BASEBALL", "FOOTBALL", "SOFTBALL", "VOLLEYBALL", "HANDBALL", "NETBALL", "BADMINTON", "SKATING", "RUNNING", "SWIMMING",

  // --- PLACES & BUILDINGS ---
  "HOUSE", "OFFICE", "SCHOOL", "MARKET", "CHURCH", "TEMPLE", "MOSQUE", "MUSEUM", "CINEMA", "THEATER",
  "STADIUM", "ARENA", "AIRPORT", "STATION", "GARAGE", "HOTEL", "RESORT", "CASINO", "PRISON", "CASTLE",
  "PALACE", "CABIN", "COTTAGE", "MANSION", "VILLA", "FACTORY", "WORKSHOP", "STUDIO", "LIBRARY", "CLINIC",
  "BAKERY", "CAFE", "RESTAURANT", "BARN", "STABLE", "SHED", "TOWER", "BRIDGE", "TUNNEL", "STREET",
  "AVENUE", "ROADSIDE", "HIGHWAY", "PARKING", "ALLEY", "GARDEN", "PARK", "PLAYGROUND", "ZOO", "AQUARIUM",

  // --- GEOGRAPHY & NATURE ---
  "MOUNTAIN", "VALLEY", "DESERT", "FOREST", "JUNGLE", "ISLAND", "BEACH", "COAST", "OCEAN", "RIVER",
  "STREAM", "STREAM", "WATERFALL", "CANYON", "VOLCANO", "MEADOW", "PRARIE", "SWAMP", "MARSH", "CAVE",
  "PLANET", "GALAXY", "NEBULA", "COMET", "METEOR", "ASTEROID", "ECLIPSE", "HORIZON", "SKYLINE", "CLOUDBURST",

  // --- NAMES (COMMON DAILY NAMES) ---
  "JAMES", "JOHN", "ROBERT", "MICHAEL", "WILLIAM", "DAVID", "RICHARD", "JOSEPH", "THOMAS", "CHARLES",
  "CHRISTOPHER", "DANIEL", "MATTHEW", "ANTHONY", "MARK", "DONALD", "STEVEN", "PAUL", "ANDREW", "JOSHUA",
  "MARY", "PATRICIA", "JENNIFER", "LINDA", "ELIZABETH", "BARBARA", "SUSAN", "JESSICA", "SARAH", "KAREN",
  "NANCY", "LISA", "BETTY", "MARGARET", "SANDRA", "ASHLEY", "KIMBERLY", "EMILY", "DONNA", "MICHELLE",
  "KEVIN", "JASON", "BRIAN", "JEFFREY", "TIMOTHY", "GARY", "RYAN", "NICHOLAS", "ERIC", "STEPHEN",
  "AMANDA", "MELISSA", "DEBORAH", "STEPHANIE", "REBECCA", "SHARON", "CYNTHIA", "KATHLEEN", "AMY", "ANNA",

  // --- EVERYDAY OBJECTS & HOUSEHOLD ITEMS ---
  "TABLE", "CHAIR", "COUCH", "DESK", "BEDSTEAD", "PILLOW", "BLANKET", "SHEET", "CLOSET", "DRAWER",
  "WINDOW", "CURTAIN", "CARPET", "MIRROR", "CLOCK", "WATCH", "LAMP", "LIGHT", "SWITCH", "SOCKET",
  "PHONE", "LAPTOP", "TABLET", "CAMERA", "SCREEN", "KEYBOARD", "MOUSE", "CABLE", "CHARGER", "BATTERY",
  "REFRIGERATOR", "OVEN", "STOVE", "TOASTER", "BLENDER", "KETTLE", "COFFEE", "TEAPOT", "PLATE", "BOWL",
  "GLASS", "CUP", "MUG", "SPOON", "FORK", "KNIFE", "BOTTLE", "CANISTER", "BASKET", "BUCKET",
  "BROOM", "BRUSH", "SPONGE", "TOWEL", "SOAP", "SHAMPOO", "LOTION", "PERFUME", "RAZOR", "TOOTHBRUSH",
  "CLOTHES", "SHIRT", "PANTS", "JACKET", "COAT", "DRESS", "SKIRT", "SOCKS", "SHOES", "BOOTS",
  "HAT", "CAP", "GLOVES", "SCARF", "BELT", "BAG", "PURSE", "WALLET", "KEYCHAIN", "UMBRELLA",
  "PENCIL", "PEN", "MARKER", "ERASER", "RULER", "PAPER", "BOOK", "BINDER", "FOLDER", "NOTEBOOK",

  // --- FOOD & DRINK ---
  "BREAD", "BUTTER", "CHEESE", "MILK", "YOGURT", "CREAM", "EGG", "MEAT", "FISH", "CHICKEN",
  "RICE", "WHEAT", "FLOUR", "SUGAR", "SALT", "PEPPER", "SPICE", "HONEY", "JAM", "SAUCE",
  "APPLE", "BANANA", "ORANGE", "GRAPE", "LEMON", "LIME", "MANGO", "PEACH", "PEAR", "BERRY",
  "MELON", "WATERMELON", "CHERRY", "BERRY", "PLUM", "APRICOT", "KIWI", "PAPAYA", "FIG", "DATE",
  "POTATO", "TOMATO", "ONION", "GARLIC", "CARROT", "BROCCOLI", "SPINACH", "LETTUCE", "CUCUMBER", "PEPPER",
  "CORN", "BEAN", "PEA", "NUT", "PEANUT", "ALMOND", "WALNUT", "CASHEW", "SEED", "GRAIN",
  "WATER", "JUICE", "SODA", "COFFEE", "TEA", "MILK", "WINE", "BEER", "CIDER", "SYRUP",
  "CAKE", "COOKIE", "PIE", "TART", "DONUT", "PASTRY", "CANDY", "CHOCOLATE", "CREAM", "HONEY",

  // --- VEHICLES & TRANSPORT ---
  "TRAIN", "TRUCK", "WAGON", "WHEEL", "YACHT", "PLANE", "GLIDER", "SCOOTER", "BICYCLE", "SUBWAY",
  "CRUISE", "ROCKET", "SHUTTLE", "TRACTOR", "TANKER", "FERRY", "ROVER", "BLIMP", "CARRIAGE", "CHARIOT",

  // --- GENERAL EVERYDAY WORDS ---
  "HAPPY", "SAD", "ANGRY", "EXCITED", "TIRED", "SLEEPY", "HUNGRY", "THIRSTY", "BRAVE", "SMART",
  "FUNNY", "SILLY", "KIND", "SWEET", "NICE", "GOOD", "BAD", "GREAT", "AWESOME", "COOL",
  "HOT", "COLD", "WARM", "COOL", "WINDY", "RAINY", "SUNNY", "CLOUDY", "STORMY", "SNOWY",
  "MORNING", "AFTERNOON", "EVENING", "NIGHT", "MIDNIGHT", "MIDDAY", "TODAY", "YESTERDAY", "TOMORROW", "WEEKEND",
  "SPRING", "SUMMER", "AUTUMN", "WINTER", "SEASON", "WEATHER", "CLIMATE", "NATURE", "WORLD", "EARTH"
];

export default wordBank